[client]
showSidebarNavigation = false

[server]
runOnSave = true
headless = true

[theme]
# Primary accent for interactive elements
primaryColor = "#bd3f19"

# Background color for the main content area
backgroundColor = "#AEC8A4"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#E7EFC7"

# Color used for almost all text
# textColor = '#645e5b'
textColor = '#3B3B1A'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "monospace"
headingFont = "serif"

# The radius used as basis for the corners of most UI elements. This can
# be one of the following: "none", "small", "medium", "large", "full",
# or the number in pixels or rem. For example, you can use "10px",
# "0.5rem", or "2rem". To follow best practices, use rem instead of
# pixels when specifying a numeric size.
baseRadius = "1rem"

# The color of the border around elements.
borderColor = "#000000"

# Whether to show a border around input widgets.
showWidgetBorder = false

# Sets the root font size (in pixels) for the app, which determines the
# overall scale of text and UI elements. The default base font size is 16.
baseFontSize = 16

# Whether to show a vertical separator between the sidebar and the main
# content area.
showSidebarBorder = true


[theme.sidebar]
baseRadius = "0.5rem"
